name: vila_mil
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.26.*
  - pandas=2.2.*
  - scipy=1.13.*
  - scikit-learn=1.5.*
  - matplotlib=3.9.*
  - pillow=10.4.*
  - h5py=3.11.*
  - tqdm=4.66.*
  - opencv=4.10.*
  - openslide=4.0.*
  - openslide-python=1.3.*
  - pyvips=2.2.*
  - libvips=8.15.*
  - tifffile=2024.*
  - pytorch=2.4.1
  - torchvision=0.19.1
  - torchaudio=2.4.1
  - pytorch-cuda=12.1
  - pip:
      - open_clip_torch==2.26.1
      - transformers==4.46.3
      - huggingface_hub==0.26.2
      - safetensors==0.4.5
      - ftfy==6.3.1
      - regex==2024.11.6
      - ml-collections==0.1.1
      - torchsummary==1.5.1
      - git+https://github.com/openai/CLIP.git
